# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Eat, Ship and Go Home
email: ghurson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog for people who don't want to sleep at the office.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://45.55.166.48" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Exclude
exclude: [feed.xml, readme.md, /css/main.css]